# Generated by Django 3.2 on 2023-01-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Польщователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default=1, max_length=10),
        ),
    ]
